### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by xtekky**

### CODE REVIEW

**Comment by gamedflike-byte** [comment]
https://vt.tiktok.com/ZSSCAhVj1/

**Comment by chavgaming11-star** [comment]
https://vt.tiktok.com/ZSS3fTjMj/

**Comment by marsaid459-ops** [comment]
https://vt.tiktok.com/ZSyb5oF8s/

**Comment by marsaid459-ops** [comment]
https://vt.tiktok.com/ZSyb5oF8s/

**Pull request merged**
